options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy code-push-trigger \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated

# Optionally, you can add additional steps or configurations here if needed.
